### ISSUE TITLE
Wild Card Prompt Issues

### ISSUE THREAD

**Issue by chanceoneal** [joshuaj004/nodeUno#4]
When a wild card is played, every player is prompted. Not clear yet if the color changes to the most recent input from a player, but if we can narrow the prompt to whoever's turn it is, that will resolve the issue. Otherwise it will hold up the game for everyone if someone doesn't react to the prompt.

A good resource for multiplayer game stuff: [npm - multiplayer keyword](https://www.npmjs.com/browse/keyword/multiplayer)
One of those resources that looks promising: [NodeGame-client](https://www.npmjs.com/package/nodegame-client)

**Comment by chanceoneal** [comment]
Those are definitely some interesting things to look at, but for the turn based system I'm going to look into using socket id's to differentiate users.

**Comment by joshuaj004** [comment]
The display card method was the issue, that goes out to all players, whereas only one player should be able to pick the wild color.
